In [1]:
import pandas as pd

## Series

In [2]:
labels = "A B C".split()

In [3]:
labels

['A', 'B', 'C']

In [4]:
my_data = [10,20,30]

In [5]:
import numpy as np

In [6]:
arr = np.array(my_data)

In [7]:
dt = {'A': 10, 'B': 20, 'C': 30}

In [8]:
my_data[0]

10

In [9]:
dt['A']

10

In [10]:
pd.Series(my_data)

0    10
1    20
2    30
dtype: int64

In [11]:
pd.Series(arr)

0    10
1    20
2    30
dtype: int64

In [12]:
pd.Series(dt)

A    10
B    20
C    30
dtype: int64

In [15]:
my_data2 = [30,40,50,60]

In [17]:
pd.Series(my_data) - pd.Series(my_data2)

0   -20.0
1   -20.0
2   -20.0
3     NaN
dtype: float64

## Dataframe

In [21]:
df = pd.DataFrame( np.random.randn(10).reshape(2,5),columns=['A','B','C','D','E'])

In [22]:
df

          A         B         C         D         E
0  0.043862  0.003783  0.290061  1.524958 -0.714251
1  1.480191  0.190155  0.029841  0.944323  0.361567

In [25]:
df[['B','D']]

          B         D
0  0.003783  1.524958
1  0.190155  0.944323

In [27]:
df['new'] = df['B'] + df['D']

In [28]:
df

          A         B         C         D         E       new
0  0.043862  0.003783  0.290061  1.524958 -0.714251  1.528742
1  1.480191  0.190155  0.029841  0.944323  0.361567  1.134478

In [29]:
df['B'] + df['E']

0   -0.710467
1    0.551721
dtype: float64

In [33]:
df.drop('C',axis=1,inplace=True)

In [34]:
df

          A         B         D         E       new
0  0.043862  0.003783  1.524958 -0.714251  1.528742
1  1.480191  0.190155  0.944323  0.361567  1.134478

In [35]:
df.shape

(2, 5)

In [36]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       2 non-null      float64
 1   B       2 non-null      float64
 2   D       2 non-null      float64
 3   E       2 non-null      float64
 4   new     2 non-null      float64
dtypes: float64(5)
memory usage: 208.0 bytes

In [37]:
df.describe()

              A         B         D         E       new
count  2.000000  2.000000  2.000000  2.000000  2.000000
mean   0.762027  0.096969  1.234641 -0.176342  1.331610
std    1.015638  0.131784  0.410571  0.760718  0.278787
min    0.043862  0.003783  0.944323 -0.714251  1.134478
25%    0.402945  0.050376  1.089482 -0.445296  1.233044
50%    0.762027  0.096969  1.234641 -0.176342  1.331610
75%    1.121109  0.143562  1.379799  0.092612  1.430176
max    1.480191  0.190155  1.524958  0.361567  1.528742

In [38]:
df

          A         B         D         E       new
0  0.043862  0.003783  1.524958 -0.714251  1.528742
1  1.480191  0.190155  0.944323  0.361567  1.134478

In [42]:
df.loc[:,'D'][0] = np.nan

C:\Users\Administrator\AppData\Local\Temp\ipykernel_20196\1222375574.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment.
Such chained assignment never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

Try using '.loc[row_indexer, col_indexer] = value' instead, to perform the assignment in a single step.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html#chained-assignment
  df.loc[:,'D'][0] = np.nan

In [43]:
df

          A         B         D         E       new
0  0.043862  0.003783  1.524958 -0.714251  1.528742
1  1.480191  0.190155  0.944323  0.361567  1.134478

In [44]:
df['B']

0    0.003783
1    0.190155
Name: B, dtype: float64

In [46]:
df.loc[0]

A      0.043862
B      0.003783
D      1.524958
E     -0.714251
new    1.528742
Name: 0, dtype: float64

In [47]:
df.iloc[1]

A      1.480191
B      0.190155
D      0.944323
E      0.361567
new    1.134478
Name: 1, dtype: float64

In [51]:
df.index = ['P','Q']

In [52]:
df

          A         B         D         E       new
P  0.043862  0.003783  1.524958 -0.714251  1.528742
Q  1.480191  0.190155  0.944323  0.361567  1.134478

In [54]:
df.loc['P']

A      0.043862
B      0.003783
D      1.524958
E     -0.714251
new    1.528742
Name: P, dtype: float64

In [55]:
df.iloc[0]

A      0.043862
B      0.003783
D      1.524958
E     -0.714251
new    1.528742
Name: P, dtype: float64

In [56]:
df > 0

      A     B     D      E   new
P  True  True  True  False  True
Q  True  True  True   True  True

In [58]:
df[df > 0].describe()

              A         B         D         E       new
count  2.000000  2.000000  2.000000  1.000000  2.000000
mean   0.762027  0.096969  1.234641  0.361567  1.331610
std    1.015638  0.131784  0.410571       NaN  0.278787
min    0.043862  0.003783  0.944323  0.361567  1.134478
25%    0.402945  0.050376  1.089482  0.361567  1.233044
50%    0.762027  0.096969  1.234641  0.361567  1.331610
75%    1.121109  0.143562  1.379799  0.361567  1.430176
max    1.480191  0.190155  1.524958  0.361567  1.528742

In [59]:
df2 = df[df > 0]

In [60]:
df2

          A         B         D         E       new
P  0.043862  0.003783  1.524958       NaN  1.528742
Q  1.480191  0.190155  0.944323  0.361567  1.134478

In [61]:
df2.info()

<class 'pandas.DataFrame'>
Index: 2 entries, P to Q
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       2 non-null      float64
 1   B       2 non-null      float64
 2   D       2 non-null      float64
 3   E       1 non-null      float64
 4   new     2 non-null      float64
dtypes: float64(5)
memory usage: 204.0+ bytes

In [62]:
df2.isnull()

       A      B      D      E    new
P  False  False  False   True  False
Q  False  False  False  False  False

In [64]:
df2.fillna(0)

          A         B         D         E       new
P  0.043862  0.003783  1.524958  0.000000  1.528742
Q  1.480191  0.190155  0.944323  0.361567  1.134478

In [70]:
df2.ffill()

          A         B         D         E       new
P  0.043862  0.003783  1.524958       NaN  1.528742
Q  1.480191  0.190155  0.944323  0.361567  1.134478

In [71]:
 df2.reset_index()

  index         A         B         D         E       new
0     P  0.043862  0.003783  1.524958       NaN  1.528742
1     Q  1.480191  0.190155  0.944323  0.361567  1.134478

In [72]:
ipl_df = pd.read_csv('data/IPL_Matches_2008_2022.csv')

In [74]:
ipl_df.head()

,ID,City,Date,Season,MatchNumber,Team1,Team2,Venue,TossWinner,TossDecision,SuperOver,WinningTeam,WonBy,Margin,method,Player_of_Match,Team1Players,Team2Players,Umpire1,Umpire2
0,1312200,Ahmedabad,2022-05-29,2022,Final,Rajasthan Royals,Gujarat Titans,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,bat,N,Gujarat Titans,Wickets,7.0,NaN,HH Pandya,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",CB Gaffaney,Nitin Menon
1,1312199,Ahmedabad,2022-05-27,2022,Qualifier 2,Royal Challengers Bangalore,Rajasthan Royals,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,field,N,Rajasthan Royals,Wickets,7.0,NaN,JC Buttler,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...",CB Gaffaney,Nitin Menon
2,1312198,Kolkata,2022-05-25,2022,Eliminator,Royal Challengers Bangalore,Lucknow Super Giants,"Eden Gardens, Kolkata",Lucknow Super Giants,field,N,Royal Challengers Bangalore,Runs,14.0,NaN,RM Patidar,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['Q de Kock', 'KL Rahul', 'M Vohra', 'DJ Hooda...",J Madanagopal,MA Gough
3,1312197,Kolkata,2022-05-24,2022,Qualifier 1,Rajasthan Royals,Gujarat Titans,"Eden Gardens, Kolkata",Gujarat Titans,field,N,Gujarat Titans,Wickets,7.0,NaN,DA Miller,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",BNJ Oxenford,VK Sharma
4,1304116,Mumbai,2022-05-22,2022,70,Sunrisers Hyderabad,Punjab Kings,"Wankhede Stadium, Mumbai",Sunrisers Hyderabad,bat,N,Punjab Kings,Wickets,5.0,NaN,Harpreet Brar,"['PK Garg', 'Abhishek Sharma', 'RA Tripathi', ...","['JM Bairstow', 'S Dhawan', 'M Shahrukh Khan',...",AK Chaudhary,NA Patwardhan

In [80]:
ipl_df.describe(include='all')

,ID,City,Date,Season,MatchNumber,Team1,Team2,Venue,TossWinner,TossDecision,SuperOver,WinningTeam,WonBy,Margin,method,Player_of_Match,Team1Players,Team2Players,Umpire1,Umpire2
count,9.500000e+02,899,950,950,950,950,950,950,950,950,946,946,950,932.000000,19,946,950,950,950,950
unique,NaN,33,706,15,80,18,18,49,18,2,2,18,4,NaN,1,262,932,937,58,60
top,NaN,Mumbai,2022-05-15,2013,Final,Royal Challengers Bangalore,Mumbai Indians,Eden Gardens,Mumbai Indians,field,N,Mumbai Indians,Wickets,NaN,D/L,AB de Villiers,"['JC Buttler', 'D Padikkal', 'SV Samson', 'SO ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",AK Chaudhary,S Ravi
freq,NaN,159,2,76,15,126,119,77,123,599,932,131,509,NaN,19,25,2,2,95,83
mean,8.304852e+05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,17.056867,NaN,NaN,NaN,NaN,NaN,NaN
std,3.375678e+05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,21.633109,NaN,NaN,NaN,NaN,NaN,NaN
min,3.359820e+05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.000000,NaN,NaN,NaN,NaN,NaN,NaN
25%,5.012612e+05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.000000,NaN,NaN,NaN,NaN,NaN,NaN
50%,8.297380e+05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.000000,NaN,NaN,NaN,NaN,NaN,NaN
75%,1.175372e+06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,19.000000,NaN,NaN,NaN,NaN,NaN,NaN
max,1.312200e+06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,146.000000,NaN,NaN,NaN,NaN,NaN,NaN

In [77]:
ipl_df.describe()

                 ID      Margin
count  9.500000e+02  932.000000
mean   8.304852e+05   17.056867
std    3.375678e+05   21.633109
min    3.359820e+05    1.000000
25%    5.012612e+05    6.000000
50%    8.297380e+05    8.000000
75%    1.175372e+06   19.000000
max    1.312200e+06  146.000000