In [1]:
import pandas as pd

## Series

In [2]:
labels = "A B C".split()

In [3]:
labels

['A', 'B', 'C']

In [4]:
my_data = [10,20,30]

In [5]:
import numpy as np

In [6]:
arr = np.array(my_data)

In [7]:
dt = {'A': 10, 'B': 20, 'C': 30}

In [8]:
my_data[0]

10

In [9]:
dt['A']

10

In [10]:
pd.Series(my_data)

0    10
1    20
2    30
dtype: int64

In [11]:
pd.Series(arr)

0    10
1    20
2    30
dtype: int64

In [12]:
pd.Series(dt)

A    10
B    20
C    30
dtype: int64

In [13]:
my_data2 = [30,40,50,60]

In [14]:
pd.Series(my_data) - pd.Series(my_data2)

0   -20.0
1   -20.0
2   -20.0
3     NaN
dtype: float64

## Dataframe

In [15]:
df = pd.DataFrame( np.random.randn(10).reshape(2,5),columns=['A','B','C','D','E'])

In [16]:
df

          A         B         C         D         E
0  0.886485 -1.778050  0.541329 -1.324871  1.562276
1  0.777787 -0.994006  0.692990  1.613468  0.641703

In [17]:
df[['B','D']]

          B         D
0 -1.778050 -1.324871
1 -0.994006  1.613468

In [18]:
df['new'] = df['B'] + df['D']

In [19]:
df

          A         B         C         D         E       new
0  0.886485 -1.778050  0.541329 -1.324871  1.562276 -3.102921
1  0.777787 -0.994006  0.692990  1.613468  0.641703  0.619462

In [20]:
df['B'] + df['E']

0   -0.215774
1   -0.352303
dtype: float64

In [21]:
df.drop('C',axis=1,inplace=True)

In [22]:
df

          A         B         D         E       new
0  0.886485 -1.778050 -1.324871  1.562276 -3.102921
1  0.777787 -0.994006  1.613468  0.641703  0.619462

In [23]:
df.shape

(2, 5)

In [24]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       2 non-null      float64
 1   B       2 non-null      float64
 2   D       2 non-null      float64
 3   E       2 non-null      float64
 4   new     2 non-null      float64
dtypes: float64(5)
memory usage: 208.0 bytes

In [25]:
df.describe()

              A         B         D         E       new
count  2.000000  2.000000  2.000000  2.000000  2.000000
mean   0.832136 -1.386028  0.144298  1.101989 -1.241730
std    0.076861  0.554403  2.077719  0.650943  2.632122
min    0.777787 -1.778050 -1.324871  0.641703 -3.102921
25%    0.804961 -1.582039 -0.590287  0.871846 -2.172325
50%    0.832136 -1.386028  0.144298  1.101989 -1.241730
75%    0.859310 -1.190017  0.878883  1.332132 -0.311134
max    0.886485 -0.994006  1.613468  1.562276  0.619462

In [26]:
df

          A         B         D         E       new
0  0.886485 -1.778050 -1.324871  1.562276 -3.102921
1  0.777787 -0.994006  1.613468  0.641703  0.619462

In [27]:
df.loc[:,'D'][0] = np.nan

C:\Users\Administrator\AppData\Local\Temp\ipykernel_452\1222375574.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment.
Such chained assignment never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

Try using '.loc[row_indexer, col_indexer] = value' instead, to perform the assignment in a single step.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html#chained-assignment
  df.loc[:,'D'][0] = np.nan

In [28]:
df

          A         B         D         E       new
0  0.886485 -1.778050 -1.324871  1.562276 -3.102921
1  0.777787 -0.994006  1.613468  0.641703  0.619462

In [29]:
df['B']

0   -1.778050
1   -0.994006
Name: B, dtype: float64

In [30]:
df.loc[0]

A      0.886485
B     -1.778050
D     -1.324871
E      1.562276
new   -3.102921
Name: 0, dtype: float64

In [31]:
df.iloc[1]

A      0.777787
B     -0.994006
D      1.613468
E      0.641703
new    0.619462
Name: 1, dtype: float64

In [32]:
df.index = ['P','Q']

In [33]:
df

          A         B         D         E       new
P  0.886485 -1.778050 -1.324871  1.562276 -3.102921
Q  0.777787 -0.994006  1.613468  0.641703  0.619462

In [34]:
df.loc['P']

A      0.886485
B     -1.778050
D     -1.324871
E      1.562276
new   -3.102921
Name: P, dtype: float64

In [35]:
df.iloc[0]

A      0.886485
B     -1.778050
D     -1.324871
E      1.562276
new   -3.102921
Name: P, dtype: float64

In [36]:
df > 0

      A      B      D     E    new
P  True  False  False  True  False
Q  True  False   True  True   True

In [37]:
df[df > 0].describe()

              A    B         D         E       new
count  2.000000  0.0  1.000000  2.000000  1.000000
mean   0.832136  NaN  1.613468  1.101989  0.619462
std    0.076861  NaN       NaN  0.650943       NaN
min    0.777787  NaN  1.613468  0.641703  0.619462
25%    0.804961  NaN  1.613468  0.871846  0.619462
50%    0.832136  NaN  1.613468  1.101989  0.619462
75%    0.859310  NaN  1.613468  1.332132  0.619462
max    0.886485  NaN  1.613468  1.562276  0.619462

In [38]:
df2 = df[df > 0]

In [39]:
df2

          A   B         D         E       new
P  0.886485 NaN       NaN  1.562276       NaN
Q  0.777787 NaN  1.613468  0.641703  0.619462

In [40]:
df2.info()

<class 'pandas.DataFrame'>
Index: 2 entries, P to Q
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       2 non-null      float64
 1   B       0 non-null      float64
 2   D       1 non-null      float64
 3   E       2 non-null      float64
 4   new     1 non-null      float64
dtypes: float64(5)
memory usage: 204.0+ bytes

In [41]:
df2.isnull()

       A     B      D      E    new
P  False  True   True  False   True
Q  False  True  False  False  False

In [42]:
df2.fillna(0)

          A    B         D         E       new
P  0.886485  0.0  0.000000  1.562276  0.000000
Q  0.777787  0.0  1.613468  0.641703  0.619462

In [43]:
df2.ffill()

          A   B         D         E       new
P  0.886485 NaN       NaN  1.562276       NaN
Q  0.777787 NaN  1.613468  0.641703  0.619462

In [44]:
 df2.reset_index()

  index         A   B         D         E       new
0     P  0.886485 NaN       NaN  1.562276       NaN
1     Q  0.777787 NaN  1.613468  0.641703  0.619462

In [45]:
ipl_df = pd.read_csv('data/IPL_Matches_2008_2022.csv')

In [46]:
ipl_df.head()

,ID,City,Date,Season,MatchNumber,Team1,Team2,Venue,TossWinner,TossDecision,SuperOver,WinningTeam,WonBy,Margin,method,Player_of_Match,Team1Players,Team2Players,Umpire1,Umpire2
0,1312200,Ahmedabad,2022-05-29,2022,Final,Rajasthan Royals,Gujarat Titans,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,bat,N,Gujarat Titans,Wickets,7.0,NaN,HH Pandya,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",CB Gaffaney,Nitin Menon
1,1312199,Ahmedabad,2022-05-27,2022,Qualifier 2,Royal Challengers Bangalore,Rajasthan Royals,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,field,N,Rajasthan Royals,Wickets,7.0,NaN,JC Buttler,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...",CB Gaffaney,Nitin Menon
2,1312198,Kolkata,2022-05-25,2022,Eliminator,Royal Challengers Bangalore,Lucknow Super Giants,"Eden Gardens, Kolkata",Lucknow Super Giants,field,N,Royal Challengers Bangalore,Runs,14.0,NaN,RM Patidar,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['Q de Kock', 'KL Rahul', 'M Vohra', 'DJ Hooda...",J Madanagopal,MA Gough
3,1312197,Kolkata,2022-05-24,2022,Qualifier 1,Rajasthan Royals,Gujarat Titans,"Eden Gardens, Kolkata",Gujarat Titans,field,N,Gujarat Titans,Wickets,7.0,NaN,DA Miller,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",BNJ Oxenford,VK Sharma
4,1304116,Mumbai,2022-05-22,2022,70,Sunrisers Hyderabad,Punjab Kings,"Wankhede Stadium, Mumbai",Sunrisers Hyderabad,bat,N,Punjab Kings,Wickets,5.0,NaN,Harpreet Brar,"['PK Garg', 'Abhishek Sharma', 'RA Tripathi', ...","['JM Bairstow', 'S Dhawan', 'M Shahrukh Khan',...",AK Chaudhary,NA Patwardhan

In [47]:
ipl_df.describe(include='all')

,ID,City,Date,Season,MatchNumber,Team1,Team2,Venue,TossWinner,TossDecision,SuperOver,WinningTeam,WonBy,Margin,method,Player_of_Match,Team1Players,Team2Players,Umpire1,Umpire2
count,9.500000e+02,899,950,950,950,950,950,950,950,950,946,946,950,932.000000,19,946,950,950,950,950
unique,NaN,33,706,15,80,18,18,49,18,2,2,18,4,NaN,1,262,932,937,58,60
top,NaN,Mumbai,2022-05-15,2013,Final,Royal Challengers Bangalore,Mumbai Indians,Eden Gardens,Mumbai Indians,field,N,Mumbai Indians,Wickets,NaN,D/L,AB de Villiers,"['JC Buttler', 'D Padikkal', 'SV Samson', 'SO ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",AK Chaudhary,S Ravi
freq,NaN,159,2,76,15,126,119,77,123,599,932,131,509,NaN,19,25,2,2,95,83
mean,8.304852e+05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,17.056867,NaN,NaN,NaN,NaN,NaN,NaN
std,3.375678e+05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,21.633109,NaN,NaN,NaN,NaN,NaN,NaN
min,3.359820e+05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.000000,NaN,NaN,NaN,NaN,NaN,NaN
25%,5.012612e+05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.000000,NaN,NaN,NaN,NaN,NaN,NaN
50%,8.297380e+05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.000000,NaN,NaN,NaN,NaN,NaN,NaN
75%,1.175372e+06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,19.000000,NaN,NaN,NaN,NaN,NaN,NaN
max,1.312200e+06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,146.000000,NaN,NaN,NaN,NaN,NaN,NaN

In [48]:
ipl_df.describe()

                 ID      Margin
count  9.500000e+02  932.000000
mean   8.304852e+05   17.056867
std    3.375678e+05   21.633109
min    3.359820e+05    1.000000
25%    5.012612e+05    6.000000
50%    8.297380e+05    8.000000
75%    1.175372e+06   19.000000
max    1.312200e+06  146.000000

In [ ]:
## class 3

In [49]:
ipl_df.head()

,ID,City,Date,Season,MatchNumber,Team1,Team2,Venue,TossWinner,TossDecision,SuperOver,WinningTeam,WonBy,Margin,method,Player_of_Match,Team1Players,Team2Players,Umpire1,Umpire2
0,1312200,Ahmedabad,2022-05-29,2022,Final,Rajasthan Royals,Gujarat Titans,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,bat,N,Gujarat Titans,Wickets,7.0,NaN,HH Pandya,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",CB Gaffaney,Nitin Menon
1,1312199,Ahmedabad,2022-05-27,2022,Qualifier 2,Royal Challengers Bangalore,Rajasthan Royals,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,field,N,Rajasthan Royals,Wickets,7.0,NaN,JC Buttler,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...",CB Gaffaney,Nitin Menon
2,1312198,Kolkata,2022-05-25,2022,Eliminator,Royal Challengers Bangalore,Lucknow Super Giants,"Eden Gardens, Kolkata",Lucknow Super Giants,field,N,Royal Challengers Bangalore,Runs,14.0,NaN,RM Patidar,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['Q de Kock', 'KL Rahul', 'M Vohra', 'DJ Hooda...",J Madanagopal,MA Gough
3,1312197,Kolkata,2022-05-24,2022,Qualifier 1,Rajasthan Royals,Gujarat Titans,"Eden Gardens, Kolkata",Gujarat Titans,field,N,Gujarat Titans,Wickets,7.0,NaN,DA Miller,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",BNJ Oxenford,VK Sharma
4,1304116,Mumbai,2022-05-22,2022,70,Sunrisers Hyderabad,Punjab Kings,"Wankhede Stadium, Mumbai",Sunrisers Hyderabad,bat,N,Punjab Kings,Wickets,5.0,NaN,Harpreet Brar,"['PK Garg', 'Abhishek Sharma', 'RA Tripathi', ...","['JM Bairstow', 'S Dhawan', 'M Shahrukh Khan',...",AK Chaudhary,NA Patwardhan

In [ ]:
ipl_df.info()

In [51]:
# print(f"Loaded dataset: {ipl_df.shape[0]} rows, {ipl_df.shape[1]} columns")
ipl_df.shape

(950, 20)

In [52]:
# Step 1: Header Cleaning

print(ipl_df.columns)

Index(['ID', 'City', 'Date', 'Season', 'MatchNumber', 'Team1', 'Team2',
       'Venue', 'TossWinner', 'TossDecision', 'SuperOver', 'WinningTeam',
       'WonBy', 'Margin', 'method', 'Player_of_Match', 'Team1Players',
       'Team2Players', 'Umpire1', 'Umpire2'],
      dtype='str')

In [53]:
print(ipl_df.columns.to_list())
# list(ipl_df.columns)

['ID', 'City', 'Date', 'Season', 'MatchNumber', 'Team1', 'Team2', 'Venue', 'TossWinner', 'TossDecision', 'SuperOver', 'WinningTeam', 'WonBy', 'Margin', 'method', 'Player_of_Match', 'Team1Players', 'Team2Players', 'Umpire1', 'Umpire2']

In [55]:
ipl_df.head()

,ID,City,Date,Season,MatchNumber,Team1,Team2,Venue,TossWinner,TossDecision,SuperOver,WinningTeam,WonBy,Margin,method,Player_of_Match,Team1Players,Team2Players,Umpire1,Umpire2
0,1312200,Ahmedabad,2022-05-29,2022,Final,Rajasthan Royals,Gujarat Titans,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,bat,N,Gujarat Titans,Wickets,7.0,NaN,HH Pandya,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",CB Gaffaney,Nitin Menon
1,1312199,Ahmedabad,2022-05-27,2022,Qualifier 2,Royal Challengers Bangalore,Rajasthan Royals,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,field,N,Rajasthan Royals,Wickets,7.0,NaN,JC Buttler,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...",CB Gaffaney,Nitin Menon
2,1312198,Kolkata,2022-05-25,2022,Eliminator,Royal Challengers Bangalore,Lucknow Super Giants,"Eden Gardens, Kolkata",Lucknow Super Giants,field,N,Royal Challengers Bangalore,Runs,14.0,NaN,RM Patidar,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['Q de Kock', 'KL Rahul', 'M Vohra', 'DJ Hooda...",J Madanagopal,MA Gough
3,1312197,Kolkata,2022-05-24,2022,Qualifier 1,Rajasthan Royals,Gujarat Titans,"Eden Gardens, Kolkata",Gujarat Titans,field,N,Gujarat Titans,Wickets,7.0,NaN,DA Miller,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",BNJ Oxenford,VK Sharma
4,1304116,Mumbai,2022-05-22,2022,70,Sunrisers Hyderabad,Punjab Kings,"Wankhede Stadium, Mumbai",Sunrisers Hyderabad,bat,N,Punjab Kings,Wickets,5.0,NaN,Harpreet Brar,"['PK Garg', 'Abhishek Sharma', 'RA Tripathi', ...","['JM Bairstow', 'S Dhawan', 'M Shahrukh Khan',...",AK Chaudhary,NA Patwardhan

In [56]:
ipl_df.columns = ipl_df.columns.str.lower().str.replace('_','')

In [57]:
ipl_df.columns

Index(['id', 'city', 'date', 'season', 'matchnumber', 'team1', 'team2',
       'venue', 'tosswinner', 'tossdecision', 'superover', 'winningteam',
       'wonby', 'margin', 'method', 'playerofmatch', 'team1players',
       'team2players', 'umpire1', 'umpire2'],
      dtype='str')

In [58]:
ipl_df.head()

,id,city,date,season,matchnumber,team1,team2,venue,tosswinner,tossdecision,superover,winningteam,wonby,margin,method,playerofmatch,team1players,team2players,umpire1,umpire2
0,1312200,Ahmedabad,2022-05-29,2022,Final,Rajasthan Royals,Gujarat Titans,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,bat,N,Gujarat Titans,Wickets,7.0,NaN,HH Pandya,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",CB Gaffaney,Nitin Menon
1,1312199,Ahmedabad,2022-05-27,2022,Qualifier 2,Royal Challengers Bangalore,Rajasthan Royals,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,field,N,Rajasthan Royals,Wickets,7.0,NaN,JC Buttler,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...",CB Gaffaney,Nitin Menon
2,1312198,Kolkata,2022-05-25,2022,Eliminator,Royal Challengers Bangalore,Lucknow Super Giants,"Eden Gardens, Kolkata",Lucknow Super Giants,field,N,Royal Challengers Bangalore,Runs,14.0,NaN,RM Patidar,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['Q de Kock', 'KL Rahul', 'M Vohra', 'DJ Hooda...",J Madanagopal,MA Gough
3,1312197,Kolkata,2022-05-24,2022,Qualifier 1,Rajasthan Royals,Gujarat Titans,"Eden Gardens, Kolkata",Gujarat Titans,field,N,Gujarat Titans,Wickets,7.0,NaN,DA Miller,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",BNJ Oxenford,VK Sharma
4,1304116,Mumbai,2022-05-22,2022,70,Sunrisers Hyderabad,Punjab Kings,"Wankhede Stadium, Mumbai",Sunrisers Hyderabad,bat,N,Punjab Kings,Wickets,5.0,NaN,Harpreet Brar,"['PK Garg', 'Abhishek Sharma', 'RA Tripathi', ...","['JM Bairstow', 'S Dhawan', 'M Shahrukh Khan',...",AK Chaudhary,NA Patwardhan

In [59]:
ipl_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 950 entries, 0 to 949
Data columns (total 20 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   id             950 non-null    int64
 1   city           899 non-null    str
 2   date           950 non-null    str
 3   season         950 non-null    str
 4   matchnumber    950 non-null    str
 5   team1          950 non-null    str
 6   team2          950 non-null    str
 7   venue          950 non-null    str
 8   tosswinner     950 non-null    str
 9   tossdecision   950 non-null    str
 10  superover      946 non-null    str
 11  winningteam    946 non-null    str
 12  wonby          950 non-null    str
 13  margin         932 non-null    float64
 14  method         19 non-null     str
 15  playerofmatch  946 non-null    str
 16  team1players   950 non-null    str
 17  team2players   950 non-null    str
 18  umpire1        950 non-null    str
 19  umpire2        950 non-null    str
dtypes: float64(1), int64(1), str(18)
memory usage: 148.6 KB

In [60]:
# Step 2: Type Conversion
ipl_df['date'] = pd.to_datetime(ipl_df['date'])

In [61]:
ipl_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 950 entries, 0 to 949
Data columns (total 20 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   id             950 non-null    int64
 1   city           899 non-null    str
 2   date           950 non-null    datetime64[us]
 3   season         950 non-null    str
 4   matchnumber    950 non-null    str
 5   team1          950 non-null    str
 6   team2          950 non-null    str
 7   venue          950 non-null    str
 8   tosswinner     950 non-null    str
 9   tossdecision   950 non-null    str
 10  superover      946 non-null    str
 11  winningteam    946 non-null    str
 12  wonby          950 non-null    str
 13  margin         932 non-null    float64
 14  method         19 non-null     str
 15  playerofmatch  946 non-null    str
 16  team1players   950 non-null    str
 17  team2players   950 non-null    str
 18  umpire1        950 non-null    str
 19  umpire2        950 non-null    str
dtypes: datetime64[us](1), float64(1), int64(1), str(17)
memory usage: 148.6 KB

In [62]:
ipl_df['season'] = ipl_df['season'].astype('int')

ValueError: invalid literal for int() with base 10: '2020/21'

In [63]:
ipl_df.head(2)

,id,city,date,season,matchnumber,team1,team2,venue,tosswinner,tossdecision,superover,winningteam,wonby,margin,method,playerofmatch,team1players,team2players,umpire1,umpire2
0,1312200,Ahmedabad,2022-05-29,2022,Final,Rajasthan Royals,Gujarat Titans,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,bat,N,Gujarat Titans,Wickets,7.0,NaN,HH Pandya,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",CB Gaffaney,Nitin Menon
1,1312199,Ahmedabad,2022-05-27,2022,Qualifier 2,Royal Challengers Bangalore,Rajasthan Royals,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,field,N,Rajasthan Royals,Wickets,7.0,NaN,JC Buttler,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...",CB Gaffaney,Nitin Menon

In [64]:
# step3: cleanup values

ipl_df['tosswinner'].unique()

<StringArray>
[           'Rajasthan Royals',        'Lucknow Super Giants',
              'Gujarat Titans',         'Sunrisers Hyderabad',
              'Mumbai Indians',         'Chennai Super Kings',
                'Punjab Kings',       'Kolkata Knight Riders',
 'Royal Challengers Bangalore',              'Delhi Capitals',
             'Kings XI Punjab',            'Delhi Daredevils',
      'Rising Pune Supergiant',               'Gujarat Lions',
     'Rising Pune Supergiants',               'Pune Warriors',
             'Deccan Chargers',        'Kochi Tuskers Kerala']
Length: 18, dtype: str

In [65]:
cleanup_map = {
    'Rising Pune Supergiant' : 'Rising Pune Supergiants'
}

ipl_df['tosswinner'] = ipl_df['tosswinner'].replace(cleanup_map)

In [66]:

ipl_df['tosswinner'].unique()

<StringArray>
[           'Rajasthan Royals',        'Lucknow Super Giants',
              'Gujarat Titans',         'Sunrisers Hyderabad',
              'Mumbai Indians',         'Chennai Super Kings',
                'Punjab Kings',       'Kolkata Knight Riders',
 'Royal Challengers Bangalore',              'Delhi Capitals',
             'Kings XI Punjab',            'Delhi Daredevils',
     'Rising Pune Supergiants',               'Gujarat Lions',
               'Pune Warriors',             'Deccan Chargers',
        'Kochi Tuskers Kerala']
Length: 17, dtype: str

In [67]:

ipl_df['winningteam'].unique()

<StringArray>
[             'Gujarat Titans',            'Rajasthan Royals',
 'Royal Challengers Bangalore',                'Punjab Kings',
              'Mumbai Indians',        'Lucknow Super Giants',
         'Sunrisers Hyderabad',              'Delhi Capitals',
       'Kolkata Knight Riders',         'Chennai Super Kings',
             'Kings XI Punjab',                           nan,
            'Delhi Daredevils',      'Rising Pune Supergiant',
               'Gujarat Lions',     'Rising Pune Supergiants',
               'Pune Warriors',             'Deccan Chargers',
        'Kochi Tuskers Kerala']
Length: 19, dtype: str

In [68]:
ipl_df['winningteam'] = ipl_df['winningteam'].replace(cleanup_map)

In [69]:
ipl_df['winningteam'].unique()

<StringArray>
[             'Gujarat Titans',            'Rajasthan Royals',
 'Royal Challengers Bangalore',                'Punjab Kings',
              'Mumbai Indians',        'Lucknow Super Giants',
         'Sunrisers Hyderabad',              'Delhi Capitals',
       'Kolkata Knight Riders',         'Chennai Super Kings',
             'Kings XI Punjab',                           nan,
            'Delhi Daredevils',     'Rising Pune Supergiants',
               'Gujarat Lions',               'Pune Warriors',
             'Deccan Chargers',        'Kochi Tuskers Kerala']
Length: 18, dtype: str

In [70]:
ipl_df['superover'].unique()

<StringArray>
['N', 'Y', nan]
Length: 3, dtype: str

In [71]:
bool_map = {
    'N': False,
    'Y': True
}

ipl_df['superover'] = ipl_df['superover'].map(bool_map).fillna(False)

In [72]:
ipl_df['superover'].unique()

array([False, True], dtype=object)

In [73]:
ipl_df.head(3)

,id,city,date,season,matchnumber,team1,team2,venue,tosswinner,tossdecision,superover,winningteam,wonby,margin,method,playerofmatch,team1players,team2players,umpire1,umpire2
0,1312200,Ahmedabad,2022-05-29,2022,Final,Rajasthan Royals,Gujarat Titans,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,bat,False,Gujarat Titans,Wickets,7.0,NaN,HH Pandya,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",CB Gaffaney,Nitin Menon
1,1312199,Ahmedabad,2022-05-27,2022,Qualifier 2,Royal Challengers Bangalore,Rajasthan Royals,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,field,False,Rajasthan Royals,Wickets,7.0,NaN,JC Buttler,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...",CB Gaffaney,Nitin Menon
2,1312198,Kolkata,2022-05-25,2022,Eliminator,Royal Challengers Bangalore,Lucknow Super Giants,"Eden Gardens, Kolkata",Lucknow Super Giants,field,False,Royal Challengers Bangalore,Runs,14.0,NaN,RM Patidar,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['Q de Kock', 'KL Rahul', 'M Vohra', 'DJ Hooda...",J Madanagopal,MA Gough

In [74]:
ipl_df['venue'].unique()

<StringArray>
[                    'Narendra Modi Stadium, Ahmedabad',
                                'Eden Gardens, Kolkata',
                             'Wankhede Stadium, Mumbai',
                            'Brabourne Stadium, Mumbai',
                   'Dr DY Patil Sports Academy, Mumbai',
        'Maharashtra Cricket Association Stadium, Pune',
                  'Dubai International Cricket Stadium',
                              'Sharjah Cricket Stadium',
                     'Zayed Cricket Stadium, Abu Dhabi',
                          'Arun Jaitley Stadium, Delhi',
             'MA Chidambaram Stadium, Chepauk, Chennai',
                                 'Sheikh Zayed Stadium',
                   'Rajiv Gandhi International Stadium',
  'Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket Stadium',
                               'MA Chidambaram Stadium',
         'Punjab Cricket Association IS Bindra Stadium',
                                     'Wankhede Stadium',
                                'M.Chinnaswamy Stadium',
                                 'Arun Jaitley Stadium',
                                         'Eden Gardens',
                               'Sawai Mansingh Stadium',
              'Maharashtra Cricket Association Stadium',
                               'Holkar Cricket Stadium',
            'Rajiv Gandhi International Stadium, Uppal',
                                'M Chinnaswamy Stadium',
                                     'Feroz Shah Kotla',
                                           'Green Park',
 'Punjab Cricket Association IS Bindra Stadium, Mohali',
               'Saurashtra Cricket Association Stadium',
     'Shaheed Veer Narayan Singh International Stadium',
                   'JSCA International Stadium Complex',
                                    'Brabourne Stadium',
           'Punjab Cricket Association Stadium, Mohali',
                      'MA Chidambaram Stadium, Chepauk',
                         'Sardar Patel Stadium, Motera',
                                     'Barabati Stadium',
                           'Subrata Roy Sahara Stadium',
         'Himachal Pradesh Cricket Association Stadium',
                           'Dr DY Patil Sports Academy',
                                        'Nehru Stadium',
         'Vidarbha Cricket Association Stadium, Jamtha',
                                'New Wanderers Stadium',
                                      'SuperSport Park',
                                            'Kingsmead',
                                      'OUTsurance Oval',
                                     'St George's Park',
                                'De Beers Diamond Oval',
                                         'Buffalo Park',
                                             'Newlands']
Length: 49, dtype: str

In [ ]:
ipl_df.sample(10)