In [1]:
import numpy as np
import pandas as pd

In [9]:
employees = pd.DataFrame({
    'emp_id': [101, 102, 103, 104],
    'name': ['mahadi', 'sahim', 'aydan', 'masha'],
    'dept_id': [1, 2, 3, 5]
})

employees

   emp_id    name  dept_id
0     101  mahadi        1
1     102   sahim        2
2     103   aydan        3
3     104   masha        5

In [10]:
department = pd.DataFrame({
    'dept_id': [1, 2, 3, 4],
    'dept_name': ['accounts', 'customer', 'management', 'production']
})

department

   dept_id   dept_name
0        1    accounts
1        2    customer
2        3  management
3        4  production

In [11]:
employee_with_dept = pd.merge(employees, department, on='dept_id', how='left')

employee_with_dept

   emp_id    name  dept_id   dept_name
0     101  mahadi        1    accounts
1     102   sahim        2    customer
2     103   aydan        3  management
3     104   masha        5         NaN

In [19]:
wide_df = pd.DataFrame({
    'city':    ['Dhaka', 'Chittagong'],
    'temp_am': [28, 30],
    'temp_pm': [34, 36],
    'temp_night': [25, 27]
})

melt_df = long_df.melt(
    id_vars= 'city',
    value_vars= ['temp_am', 'temp_pm', 'temp_night'],
    var_name= 'temparature',
    value_name= 'time_of_day'
)

melt_df['temparature'] = melt_df['temparature'].str.replace('temp_', '', regex=False).str.upper()


print('After melt dataframe: ')
print(melt_df)

After melt dataframe:
         city temparature  time_of_day
0       Dhaka          AM           28
1  Chittagong          AM           30
2       Dhaka          PM           34
3  Chittagong          PM           36
4       Dhaka       NIGHT           25
5  Chittagong       NIGHT           27

In [16]:
melt_df['temparature'] = melt_df['temparature'].str.replace('temp_', '', regex=False).str.upper()

melt_df

         city temparature  time_of the_day
0       Dhaka          AM               28
1  Chittagong          AM               30
2       Dhaka          PM               34
3  Chittagong          PM               36
4       Dhaka       NIGHT               25
5  Chittagong       NIGHT               27