In [1]:
import pandas as pd

# Reading csv, excel, and json files in pandas

To read csv file in pandas, you can use the `read_csv` function.
To read excel file in pandas, you can use the `read_excel` function.
To read json file in pandas, you can use the `read_json` function.

Here are examples of how to use these functions:

```df = pd.read_csv('file.csv')``` 

```df = pd.read_excel('file.xlsx')```
 
```df = pd.read_json('file.json')```

In [2]:
df = pd.read_csv("sales_data_sample.csv", encoding="latin1")

df

,ORDERNUMBER,QUANTITYORDERED,PRICEEACH,ORDERLINENUMBER,SALES,ORDERDATE,STATUS,QTR_ID,MONTH_ID,YEAR_ID,...,ADDRESSLINE1,ADDRESSLINE2,CITY,STATE,POSTALCODE,COUNTRY,TERRITORY,CONTACTLASTNAME,CONTACTFIRSTNAME,DEALSIZE
0,10107,30,95.70,2,2871.00,2/24/2003 0:00,Shipped,1,2,2003,...,897 Long Airport Avenue,NaN,NYC,NY,10022,USA,NaN,Yu,Kwai,Small
1,10121,34,81.35,5,2765.90,5/7/2003 0:00,Shipped,2,5,2003,...,59 rue de l'Abbaye,NaN,Reims,NaN,51100,France,EMEA,Henriot,Paul,Small
2,10134,41,94.74,2,3884.34,7/1/2003 0:00,Shipped,3,7,2003,...,27 rue du Colonel Pierre Avia,NaN,Paris,NaN,75508,France,EMEA,Da Cunha,Daniel,Medium
3,10145,45,83.26,6,3746.70,8/25/2003 0:00,Shipped,3,8,2003,...,78934 Hillside Dr.,NaN,Pasadena,CA,90003,USA,NaN,Young,Julie,Medium
4,10159,49,100.00,14,5205.27,10/10/2003 0:00,Shipped,4,10,2003,...,7734 Strong St.,NaN,San Francisco,CA,NaN,USA,NaN,Brown,Julie,Medium
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2818,10350,20,100.00,15,2244.40,12/2/2004 0:00,Shipped,4,12,2004,...,"C/ Moralzarzal, 86",NaN,Madrid,NaN,28034,Spain,EMEA,Freyre,Diego,Small
2819,10373,29,100.00,1,3978.51,1/31/2005 0:00,Shipped,1,1,2005,...,Torikatu 38,NaN,Oulu,NaN,90110,Finland,EMEA,Koskitalo,Pirkko,Medium
2820,10386,43,100.00,4,5417.57,3/1/2005 0:00,Resolved,1,3,2005,...,"C/ Moralzarzal, 86",NaN,Madrid,NaN,28034,Spain,EMEA,Freyre,Diego,Medium
2821,10397,34,62.24,1,2116.16,3/28/2005 0:00,Shipped,1,3,2005,...,1 rue Alsace-Lorraine,NaN,Toulouse,NaN,31000,France,EMEA,Roulet,Annette,Small
2822,10414,47,65.52,9,3079.44,5/6/2005 0:00,On Hold,2,5,2005,...,8616 Spinnaker Dr.,NaN,Boston,MA,51003,USA,NaN,Yoshido,Juri,Medium

# Creating a DataFrame from a dictionary and saving it as csv, excel, and json files

To create a DataFrame from a dictionary, you can use the `DataFrame` constructor from pandas. And we can save it as csv, excel, and json files using the `to_csv`, `to_excel`, and `to_json` methods respectively.
Here is an example of how to create a DataFrame from a dictionary and save it as different file formats:

```
data = {
    'Name': ['Alice', 'Bob', 'Charlie'],
    'Age': [25, 30, 35],
    'City': ['New York', 'Los Angeles', 'Chicago']
}```

```df = pd.DataFrame(data)

df.to_csv('file.csv', index=False)

df.to_excel('file.xlsx', index=False)

df.to_json('file.json', orient='records')```

In this example, we first create a dictionary with some sample data. Then we convert it into a DataFrame using ```pd.DataFrame()```. Finally, we save the DataFrame to a CSV file, an Excel file, and a JSON file using the respective methods. The ```index=False``` parameter is used to prevent pandas from writing row indices to the files.

In [3]:
# create dataframe and export it as csv, excel and json

data = {
    'Name': ['Alice', 'Bob', 'Charlie'],
    'Age': [25, 30, 35],
    'City': ['New York', 'Los Angeles', 'Chicago']
}

custom_df = pd.DataFrame(data)

custom_df
# here we can see row index number by default

      Name  Age         City
0    Alice   25     New York
1      Bob   30  Los Angeles
2  Charlie   35      Chicago

In [4]:
# removing the index while exporting

# to csv
custom_df.to_csv("custom_data.csv", index=False)

In [5]:
# to excel
custom_df.to_excel("custom_data.xlsx", index=False)

In [6]:
# to json
custom_df.to_json("custom_data.json", index=False)

In [7]:
# head() --> by default it show first 5 rows. head(n) --> shows n number of rows

# df = pd.read_csv("/Users/istiakislam/projects/Learning-Data-Science/pandas/sales_data_sample.csv", encoding="latin1")


df.head()

,ORDERNUMBER,QUANTITYORDERED,PRICEEACH,ORDERLINENUMBER,SALES,ORDERDATE,STATUS,QTR_ID,MONTH_ID,YEAR_ID,...,ADDRESSLINE1,ADDRESSLINE2,CITY,STATE,POSTALCODE,COUNTRY,TERRITORY,CONTACTLASTNAME,CONTACTFIRSTNAME,DEALSIZE
0,10107,30,95.70,2,2871.00,2/24/2003 0:00,Shipped,1,2,2003,...,897 Long Airport Avenue,NaN,NYC,NY,10022,USA,NaN,Yu,Kwai,Small
1,10121,34,81.35,5,2765.90,5/7/2003 0:00,Shipped,2,5,2003,...,59 rue de l'Abbaye,NaN,Reims,NaN,51100,France,EMEA,Henriot,Paul,Small
2,10134,41,94.74,2,3884.34,7/1/2003 0:00,Shipped,3,7,2003,...,27 rue du Colonel Pierre Avia,NaN,Paris,NaN,75508,France,EMEA,Da Cunha,Daniel,Medium
3,10145,45,83.26,6,3746.70,8/25/2003 0:00,Shipped,3,8,2003,...,78934 Hillside Dr.,NaN,Pasadena,CA,90003,USA,NaN,Young,Julie,Medium
4,10159,49,100.00,14,5205.27,10/10/2003 0:00,Shipped,4,10,2003,...,7734 Strong St.,NaN,San Francisco,CA,NaN,USA,NaN,Brown,Julie,Medium

In [8]:
df.head(10)

,ORDERNUMBER,QUANTITYORDERED,PRICEEACH,ORDERLINENUMBER,SALES,ORDERDATE,STATUS,QTR_ID,MONTH_ID,YEAR_ID,...,ADDRESSLINE1,ADDRESSLINE2,CITY,STATE,POSTALCODE,COUNTRY,TERRITORY,CONTACTLASTNAME,CONTACTFIRSTNAME,DEALSIZE
0,10107,30,95.70,2,2871.00,2/24/2003 0:00,Shipped,1,2,2003,...,897 Long Airport Avenue,NaN,NYC,NY,10022,USA,NaN,Yu,Kwai,Small
1,10121,34,81.35,5,2765.90,5/7/2003 0:00,Shipped,2,5,2003,...,59 rue de l'Abbaye,NaN,Reims,NaN,51100,France,EMEA,Henriot,Paul,Small
2,10134,41,94.74,2,3884.34,7/1/2003 0:00,Shipped,3,7,2003,...,27 rue du Colonel Pierre Avia,NaN,Paris,NaN,75508,France,EMEA,Da Cunha,Daniel,Medium
3,10145,45,83.26,6,3746.70,8/25/2003 0:00,Shipped,3,8,2003,...,78934 Hillside Dr.,NaN,Pasadena,CA,90003,USA,NaN,Young,Julie,Medium
4,10159,49,100.00,14,5205.27,10/10/2003 0:00,Shipped,4,10,2003,...,7734 Strong St.,NaN,San Francisco,CA,NaN,USA,NaN,Brown,Julie,Medium
5,10168,36,96.66,1,3479.76,10/28/2003 0:00,Shipped,4,10,2003,...,9408 Furth Circle,NaN,Burlingame,CA,94217,USA,NaN,Hirano,Juri,Medium
6,10180,29,86.13,9,2497.77,11/11/2003 0:00,Shipped,4,11,2003,...,"184, chausse de Tournai",NaN,Lille,NaN,59000,France,EMEA,Rance,Martine,Small
7,10188,48,100.00,1,5512.32,11/18/2003 0:00,Shipped,4,11,2003,...,"Drammen 121, PR 744 Sentrum",NaN,Bergen,NaN,N 5804,Norway,EMEA,Oeztan,Veysel,Medium
8,10201,22,98.57,2,2168.54,12/1/2003 0:00,Shipped,4,12,2003,...,5557 North Pendale Street,NaN,San Francisco,CA,NaN,USA,NaN,Murphy,Julie,Small
9,10211,41,100.00,14,4708.44,1/15/2004 0:00,Shipped,1,1,2004,...,"25, rue Lauriston",NaN,Paris,NaN,75016,France,EMEA,Perrier,Dominique,Medium

In [9]:
# tail(n) --> by default it shows last 5 rows and if provide n then it shows last n number of rows

df.tail(10)

,ORDERNUMBER,QUANTITYORDERED,PRICEEACH,ORDERLINENUMBER,SALES,ORDERDATE,STATUS,QTR_ID,MONTH_ID,YEAR_ID,...,ADDRESSLINE1,ADDRESSLINE2,CITY,STATE,POSTALCODE,COUNTRY,TERRITORY,CONTACTLASTNAME,CONTACTFIRSTNAME,DEALSIZE
2813,10293,32,60.06,1,1921.92,9/9/2004 0:00,Shipped,3,9,2004,...,Via Monte Bianco 34,NaN,Torino,NaN,10100,Italy,EMEA,Accorti,Paolo,Small
2814,10306,35,59.51,6,2082.85,10/14/2004 0:00,Shipped,4,10,2004,...,Fauntleroy Circus,NaN,Manchester,NaN,EC2 5NT,UK,EMEA,Ashworth,Victoria,Small
2815,10315,40,55.69,5,2227.60,10/29/2004 0:00,Shipped,4,10,2004,...,"67, rue des Cinquante Otages",NaN,Nantes,NaN,44000,France,EMEA,Labrune,Janine,Small
2816,10327,37,86.74,4,3209.38,11/10/2004 0:00,Resolved,4,11,2004,...,Vinb'ltet 34,NaN,Kobenhavn,NaN,1734,Denmark,EMEA,Petersen,Jytte,Medium
2817,10337,42,97.16,5,4080.72,11/21/2004 0:00,Shipped,4,11,2004,...,5905 Pompton St.,Suite 750,NYC,NY,10022,USA,NaN,Hernandez,Maria,Medium
2818,10350,20,100.00,15,2244.40,12/2/2004 0:00,Shipped,4,12,2004,...,"C/ Moralzarzal, 86",NaN,Madrid,NaN,28034,Spain,EMEA,Freyre,Diego,Small
2819,10373,29,100.00,1,3978.51,1/31/2005 0:00,Shipped,1,1,2005,...,Torikatu 38,NaN,Oulu,NaN,90110,Finland,EMEA,Koskitalo,Pirkko,Medium
2820,10386,43,100.00,4,5417.57,3/1/2005 0:00,Resolved,1,3,2005,...,"C/ Moralzarzal, 86",NaN,Madrid,NaN,28034,Spain,EMEA,Freyre,Diego,Medium
2821,10397,34,62.24,1,2116.16,3/28/2005 0:00,Shipped,1,3,2005,...,1 rue Alsace-Lorraine,NaN,Toulouse,NaN,31000,France,EMEA,Roulet,Annette,Small
2822,10414,47,65.52,9,3079.44,5/6/2005 0:00,On Hold,2,5,2005,...,8616 Spinnaker Dr.,NaN,Boston,MA,51003,USA,NaN,Yoshido,Juri,Medium

# `info()`, `shape`, and `describe()` methods in pandas

Number of rows and columns in a DataFrame can be obtained using the `shape` attribute. The `shape` attribute returns a tuple where the first element is the number of rows and the second element is the number of columns.

And `info()` method provides a concise summary of the DataFrame, including the number of non-null entries, data types of each column, and memory usage.

The `describe()` method provides a statistical summary of the DataFrame, including count, mean, standard deviation, minimum, 25th percentile, median (50th percentile), 75th percentile, and maximum values for each numeric column.

Then `columns` attribute returns the column labels of the DataFrame as an Index object.

In [10]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2823 entries, 0 to 2822
Data columns (total 25 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   ORDERNUMBER       2823 non-null   int64
 1   QUANTITYORDERED   2823 non-null   int64
 2   PRICEEACH         2823 non-null   float64
 3   ORDERLINENUMBER   2823 non-null   int64
 4   SALES             2823 non-null   float64
 5   ORDERDATE         2823 non-null   str
 6   STATUS            2823 non-null   str
 7   QTR_ID            2823 non-null   int64
 8   MONTH_ID          2823 non-null   int64
 9   YEAR_ID           2823 non-null   int64
 10  PRODUCTLINE       2823 non-null   str
 11  MSRP              2823 non-null   int64
 12  PRODUCTCODE       2823 non-null   str
 13  CUSTOMERNAME      2823 non-null   str
 14  PHONE             2823 non-null   str
 15  ADDRESSLINE1      2823 non-null   str
 16  ADDRESSLINE2      302 non-null    str
 17  CITY              2823 non-null   str
 18  STATE             1337 non-null   str
 19  POSTALCODE        2747 non-null   str
 20  COUNTRY           2823 non-null   str
 21  TERRITORY         1749 non-null   str
 22  CONTACTLASTNAME   2823 non-null   str
 23  CONTACTFIRSTNAME  2823 non-null   str
 24  DEALSIZE          2823 non-null   str
dtypes: float64(2), int64(7), str(16)
memory usage: 551.5 KB

In [11]:
df.shape # shows number of rows and column

(2823, 25)

In [12]:

df.shape[0] # shows the number of rows only

2823

In [13]:

df.shape[1] # shows the number of columns only

25

In [14]:
df.describe()

,ORDERNUMBER,QUANTITYORDERED,PRICEEACH,ORDERLINENUMBER,SALES,QTR_ID,MONTH_ID,YEAR_ID,MSRP
count,2823.000000,2823.000000,2823.000000,2823.000000,2823.000000,2823.000000,2823.000000,2823.00000,2823.000000
mean,10258.725115,35.092809,83.658544,6.466171,3553.889072,2.717676,7.092455,2003.81509,100.715551
std,92.085478,9.741443,20.174277,4.225841,1841.865106,1.203878,3.656633,0.69967,40.187912
min,10100.000000,6.000000,26.880000,1.000000,482.130000,1.000000,1.000000,2003.00000,33.000000
25%,10180.000000,27.000000,68.860000,3.000000,2203.430000,2.000000,4.000000,2003.00000,68.000000
50%,10262.000000,35.000000,95.700000,6.000000,3184.800000,3.000000,8.000000,2004.00000,99.000000
75%,10333.500000,43.000000,100.000000,9.000000,4508.000000,4.000000,11.000000,2004.00000,124.000000
max,10425.000000,97.000000,100.000000,18.000000,14082.800000,4.000000,12.000000,2005.00000,214.000000

In [15]:
# shows all the columns names
df.columns

Index(['ORDERNUMBER', 'QUANTITYORDERED', 'PRICEEACH', 'ORDERLINENUMBER',
       'SALES', 'ORDERDATE', 'STATUS', 'QTR_ID', 'MONTH_ID', 'YEAR_ID',
       'PRODUCTLINE', 'MSRP', 'PRODUCTCODE', 'CUSTOMERNAME', 'PHONE',
       'ADDRESSLINE1', 'ADDRESSLINE2', 'CITY', 'STATE', 'POSTALCODE',
       'COUNTRY', 'TERRITORY', 'CONTACTLASTNAME', 'CONTACTFIRSTNAME',
       'DEALSIZE'],
      dtype='str')

select a

In [16]:
# select a column --> this will return a series of dataframe
df["SALES"]

0       2871.00
1       2765.90
2       3884.34
3       3746.70
4       5205.27
         ...
2818    2244.40
2819    3978.51
2820    5417.57
2821    2116.16
2822    3079.44
Name: SALES, Length: 2823, dtype: float64

In [17]:
# select multiple column --> this way inside [] will return as dataframe
df[["STATUS", "CITY"]]

        STATUS           CITY
0      Shipped            NYC
1      Shipped          Reims
2      Shipped          Paris
3      Shipped       Pasadena
4      Shipped  San Francisco
...        ...            ...
2818   Shipped         Madrid
2819   Shipped           Oulu
2820  Resolved         Madrid
2821   Shipped       Toulouse
2822   On Hold         Boston

[2823 rows x 2 columns]

In [18]:
# simple row filtering

df[(df["STATUS"] == 'On Hold') & (df["QTR_ID"] > 3)]

,ORDERNUMBER,QUANTITYORDERED,PRICEEACH,ORDERLINENUMBER,SALES,ORDERDATE,STATUS,QTR_ID,MONTH_ID,YEAR_ID,...,ADDRESSLINE1,ADDRESSLINE2,CITY,STATE,POSTALCODE,COUNTRY,TERRITORY,CONTACTLASTNAME,CONTACTFIRSTNAME,DEALSIZE
153,10334,26,100.00,2,3188.12,11/19/2004 0:00,On Hold,4,11,2004,...,Berguvsvgen 8,NaN,Lule,NaN,S-958 22,Sweden,EMEA,Berglund,Christina,Medium
721,10334,46,100.00,6,5814.86,11/19/2004 0:00,On Hold,4,11,2004,...,Berguvsvgen 8,NaN,Lule,NaN,S-958 22,Sweden,EMEA,Berglund,Christina,Medium
773,10334,34,61.38,1,2086.92,11/19/2004 0:00,On Hold,4,11,2004,...,Berguvsvgen 8,NaN,Lule,NaN,S-958 22,Sweden,EMEA,Berglund,Christina,Small
1052,10334,20,100.00,3,2878.80,11/19/2004 0:00,On Hold,4,11,2004,...,Berguvsvgen 8,NaN,Lule,NaN,S-958 22,Sweden,EMEA,Berglund,Christina,Small
1335,10334,49,100.00,4,6763.47,11/19/2004 0:00,On Hold,4,11,2004,...,Berguvsvgen 8,NaN,Lule,NaN,S-958 22,Sweden,EMEA,Berglund,Christina,Medium
1661,10334,42,100.00,5,5528.04,11/19/2004 0:00,On Hold,4,11,2004,...,Berguvsvgen 8,NaN,Lule,NaN,S-958 22,Sweden,EMEA,Berglund,Christina,Medium

In [19]:
df[(df["QTR_ID"] > 3) | (df["STATUS"] == 'On Hold') ]

,ORDERNUMBER,QUANTITYORDERED,PRICEEACH,ORDERLINENUMBER,SALES,ORDERDATE,STATUS,QTR_ID,MONTH_ID,YEAR_ID,...,ADDRESSLINE1,ADDRESSLINE2,CITY,STATE,POSTALCODE,COUNTRY,TERRITORY,CONTACTLASTNAME,CONTACTFIRSTNAME,DEALSIZE
4,10159,49,100.00,14,5205.27,10/10/2003 0:00,Shipped,4,10,2003,...,7734 Strong St.,NaN,San Francisco,CA,NaN,USA,NaN,Brown,Julie,Medium
5,10168,36,96.66,1,3479.76,10/28/2003 0:00,Shipped,4,10,2003,...,9408 Furth Circle,NaN,Burlingame,CA,94217,USA,NaN,Hirano,Juri,Medium
6,10180,29,86.13,9,2497.77,11/11/2003 0:00,Shipped,4,11,2003,...,"184, chausse de Tournai",NaN,Lille,NaN,59000,France,EMEA,Rance,Martine,Small
7,10188,48,100.00,1,5512.32,11/18/2003 0:00,Shipped,4,11,2003,...,"Drammen 121, PR 744 Sentrum",NaN,Bergen,NaN,N 5804,Norway,EMEA,Oeztan,Veysel,Medium
8,10201,22,98.57,2,2168.54,12/1/2003 0:00,Shipped,4,12,2003,...,5557 North Pendale Street,NaN,San Francisco,CA,NaN,USA,NaN,Murphy,Julie,Small
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2815,10315,40,55.69,5,2227.60,10/29/2004 0:00,Shipped,4,10,2004,...,"67, rue des Cinquante Otages",NaN,Nantes,NaN,44000,France,EMEA,Labrune,Janine,Small
2816,10327,37,86.74,4,3209.38,11/10/2004 0:00,Resolved,4,11,2004,...,Vinb'ltet 34,NaN,Kobenhavn,NaN,1734,Denmark,EMEA,Petersen,Jytte,Medium
2817,10337,42,97.16,5,4080.72,11/21/2004 0:00,Shipped,4,11,2004,...,5905 Pompton St.,Suite 750,NYC,NY,10022,USA,NaN,Hernandez,Maria,Medium
2818,10350,20,100.00,15,2244.40,12/2/2004 0:00,Shipped,4,12,2004,...,"C/ Moralzarzal, 86",NaN,Madrid,NaN,28034,Spain,EMEA,Freyre,Diego,Small
2822,10414,47,65.52,9,3079.44,5/6/2005 0:00,On Hold,2,5,2005,...,8616 Spinnaker Dr.,NaN,Boston,MA,51003,USA,NaN,Yoshido,Juri,Medium

# Modifying and advanced filtering DataFrame in pandas

* Add a column to a DataFrame: You can add a new column to a DataFrame by assigning a value to a new column name. For example, `df['New_Column'] = value` will add a new column named 'New_Column' with the specified value. This value can be a constant, a list, or a result of an operation on existing columns. The new column will be added at the end of the DataFrame.
* Another way is inserting a column at a specific position using the `insert()` method. For example, `df.insert(loc=1, column='New_Column', value=value)` will insert a new column named 'New_Column' at index 1 (second position) with the specified value.

In [20]:
df["DISCOUNT"] = df["PRICEEACH"] * 0.90

df

,ORDERNUMBER,QUANTITYORDERED,PRICEEACH,ORDERLINENUMBER,SALES,ORDERDATE,STATUS,QTR_ID,MONTH_ID,YEAR_ID,...,ADDRESSLINE2,CITY,STATE,POSTALCODE,COUNTRY,TERRITORY,CONTACTLASTNAME,CONTACTFIRSTNAME,DEALSIZE,DISCOUNT
0,10107,30,95.70,2,2871.00,2/24/2003 0:00,Shipped,1,2,2003,...,NaN,NYC,NY,10022,USA,NaN,Yu,Kwai,Small,86.130
1,10121,34,81.35,5,2765.90,5/7/2003 0:00,Shipped,2,5,2003,...,NaN,Reims,NaN,51100,France,EMEA,Henriot,Paul,Small,73.215
2,10134,41,94.74,2,3884.34,7/1/2003 0:00,Shipped,3,7,2003,...,NaN,Paris,NaN,75508,France,EMEA,Da Cunha,Daniel,Medium,85.266
3,10145,45,83.26,6,3746.70,8/25/2003 0:00,Shipped,3,8,2003,...,NaN,Pasadena,CA,90003,USA,NaN,Young,Julie,Medium,74.934
4,10159,49,100.00,14,5205.27,10/10/2003 0:00,Shipped,4,10,2003,...,NaN,San Francisco,CA,NaN,USA,NaN,Brown,Julie,Medium,90.000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2818,10350,20,100.00,15,2244.40,12/2/2004 0:00,Shipped,4,12,2004,...,NaN,Madrid,NaN,28034,Spain,EMEA,Freyre,Diego,Small,90.000
2819,10373,29,100.00,1,3978.51,1/31/2005 0:00,Shipped,1,1,2005,...,NaN,Oulu,NaN,90110,Finland,EMEA,Koskitalo,Pirkko,Medium,90.000
2820,10386,43,100.00,4,5417.57,3/1/2005 0:00,Resolved,1,3,2005,...,NaN,Madrid,NaN,28034,Spain,EMEA,Freyre,Diego,Medium,90.000
2821,10397,34,62.24,1,2116.16,3/28/2005 0:00,Shipped,1,3,2005,...,NaN,Toulouse,NaN,31000,France,EMEA,Roulet,Annette,Small,56.016
2822,10414,47,65.52,9,3079.44,5/6/2005 0:00,On Hold,2,5,2005,...,NaN,Boston,MA,51003,USA,NaN,Yoshido,Juri,Medium,58.968

In [21]:
df[["PRICEEACH", "DISCOUNT"]]

      PRICEEACH  DISCOUNT
0         95.70    86.130
1         81.35    73.215
2         94.74    85.266
3         83.26    74.934
4        100.00    90.000
...         ...       ...
2818     100.00    90.000
2819     100.00    90.000
2820     100.00    90.000
2821      62.24    56.016
2822      65.52    58.968

[2823 rows x 2 columns]

In [22]:
# single column reorder using pop and insert

col = df.pop("DISCOUNT")

df.insert(3, "DISCOUNT", col)

df

,ORDERNUMBER,QUANTITYORDERED,PRICEEACH,DISCOUNT,ORDERLINENUMBER,SALES,ORDERDATE,STATUS,QTR_ID,MONTH_ID,...,ADDRESSLINE1,ADDRESSLINE2,CITY,STATE,POSTALCODE,COUNTRY,TERRITORY,CONTACTLASTNAME,CONTACTFIRSTNAME,DEALSIZE
0,10107,30,95.70,86.130,2,2871.00,2/24/2003 0:00,Shipped,1,2,...,897 Long Airport Avenue,NaN,NYC,NY,10022,USA,NaN,Yu,Kwai,Small
1,10121,34,81.35,73.215,5,2765.90,5/7/2003 0:00,Shipped,2,5,...,59 rue de l'Abbaye,NaN,Reims,NaN,51100,France,EMEA,Henriot,Paul,Small
2,10134,41,94.74,85.266,2,3884.34,7/1/2003 0:00,Shipped,3,7,...,27 rue du Colonel Pierre Avia,NaN,Paris,NaN,75508,France,EMEA,Da Cunha,Daniel,Medium
3,10145,45,83.26,74.934,6,3746.70,8/25/2003 0:00,Shipped,3,8,...,78934 Hillside Dr.,NaN,Pasadena,CA,90003,USA,NaN,Young,Julie,Medium
4,10159,49,100.00,90.000,14,5205.27,10/10/2003 0:00,Shipped,4,10,...,7734 Strong St.,NaN,San Francisco,CA,NaN,USA,NaN,Brown,Julie,Medium
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2818,10350,20,100.00,90.000,15,2244.40,12/2/2004 0:00,Shipped,4,12,...,"C/ Moralzarzal, 86",NaN,Madrid,NaN,28034,Spain,EMEA,Freyre,Diego,Small
2819,10373,29,100.00,90.000,1,3978.51,1/31/2005 0:00,Shipped,1,1,...,Torikatu 38,NaN,Oulu,NaN,90110,Finland,EMEA,Koskitalo,Pirkko,Medium
2820,10386,43,100.00,90.000,4,5417.57,3/1/2005 0:00,Resolved,1,3,...,"C/ Moralzarzal, 86",NaN,Madrid,NaN,28034,Spain,EMEA,Freyre,Diego,Medium
2821,10397,34,62.24,56.016,1,2116.16,3/28/2005 0:00,Shipped,1,3,...,1 rue Alsace-Lorraine,NaN,Toulouse,NaN,31000,France,EMEA,Roulet,Annette,Small
2822,10414,47,65.52,58.968,9,3079.44,5/6/2005 0:00,On Hold,2,5,...,8616 Spinnaker Dr.,NaN,Boston,MA,51003,USA,NaN,Yoshido,Juri,Medium

In [23]:
df.insert(3, "DISCOUNT_PERCENT", 10)
df

,ORDERNUMBER,QUANTITYORDERED,PRICEEACH,DISCOUNT_PERCENT,DISCOUNT,ORDERLINENUMBER,SALES,ORDERDATE,STATUS,QTR_ID,...,ADDRESSLINE1,ADDRESSLINE2,CITY,STATE,POSTALCODE,COUNTRY,TERRITORY,CONTACTLASTNAME,CONTACTFIRSTNAME,DEALSIZE
0,10107,30,95.70,10,86.130,2,2871.00,2/24/2003 0:00,Shipped,1,...,897 Long Airport Avenue,NaN,NYC,NY,10022,USA,NaN,Yu,Kwai,Small
1,10121,34,81.35,10,73.215,5,2765.90,5/7/2003 0:00,Shipped,2,...,59 rue de l'Abbaye,NaN,Reims,NaN,51100,France,EMEA,Henriot,Paul,Small
2,10134,41,94.74,10,85.266,2,3884.34,7/1/2003 0:00,Shipped,3,...,27 rue du Colonel Pierre Avia,NaN,Paris,NaN,75508,France,EMEA,Da Cunha,Daniel,Medium
3,10145,45,83.26,10,74.934,6,3746.70,8/25/2003 0:00,Shipped,3,...,78934 Hillside Dr.,NaN,Pasadena,CA,90003,USA,NaN,Young,Julie,Medium
4,10159,49,100.00,10,90.000,14,5205.27,10/10/2003 0:00,Shipped,4,...,7734 Strong St.,NaN,San Francisco,CA,NaN,USA,NaN,Brown,Julie,Medium
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2818,10350,20,100.00,10,90.000,15,2244.40,12/2/2004 0:00,Shipped,4,...,"C/ Moralzarzal, 86",NaN,Madrid,NaN,28034,Spain,EMEA,Freyre,Diego,Small
2819,10373,29,100.00,10,90.000,1,3978.51,1/31/2005 0:00,Shipped,1,...,Torikatu 38,NaN,Oulu,NaN,90110,Finland,EMEA,Koskitalo,Pirkko,Medium
2820,10386,43,100.00,10,90.000,4,5417.57,3/1/2005 0:00,Resolved,1,...,"C/ Moralzarzal, 86",NaN,Madrid,NaN,28034,Spain,EMEA,Freyre,Diego,Medium
2821,10397,34,62.24,10,56.016,1,2116.16,3/28/2005 0:00,Shipped,1,...,1 rue Alsace-Lorraine,NaN,Toulouse,NaN,31000,France,EMEA,Roulet,Annette,Small
2822,10414,47,65.52,10,58.968,9,3079.44,5/6/2005 0:00,On Hold,2,...,8616 Spinnaker Dr.,NaN,Boston,MA,51003,USA,NaN,Yoshido,Juri,Medium

In [24]:
# update a specific row value in a dataframe

df.loc[1, "PRICEEACH"] = 85.5

df

,ORDERNUMBER,QUANTITYORDERED,PRICEEACH,DISCOUNT_PERCENT,DISCOUNT,ORDERLINENUMBER,SALES,ORDERDATE,STATUS,QTR_ID,...,ADDRESSLINE1,ADDRESSLINE2,CITY,STATE,POSTALCODE,COUNTRY,TERRITORY,CONTACTLASTNAME,CONTACTFIRSTNAME,DEALSIZE
0,10107,30,95.70,10,86.130,2,2871.00,2/24/2003 0:00,Shipped,1,...,897 Long Airport Avenue,NaN,NYC,NY,10022,USA,NaN,Yu,Kwai,Small
1,10121,34,85.50,10,73.215,5,2765.90,5/7/2003 0:00,Shipped,2,...,59 rue de l'Abbaye,NaN,Reims,NaN,51100,France,EMEA,Henriot,Paul,Small
2,10134,41,94.74,10,85.266,2,3884.34,7/1/2003 0:00,Shipped,3,...,27 rue du Colonel Pierre Avia,NaN,Paris,NaN,75508,France,EMEA,Da Cunha,Daniel,Medium
3,10145,45,83.26,10,74.934,6,3746.70,8/25/2003 0:00,Shipped,3,...,78934 Hillside Dr.,NaN,Pasadena,CA,90003,USA,NaN,Young,Julie,Medium
4,10159,49,100.00,10,90.000,14,5205.27,10/10/2003 0:00,Shipped,4,...,7734 Strong St.,NaN,San Francisco,CA,NaN,USA,NaN,Brown,Julie,Medium
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2818,10350,20,100.00,10,90.000,15,2244.40,12/2/2004 0:00,Shipped,4,...,"C/ Moralzarzal, 86",NaN,Madrid,NaN,28034,Spain,EMEA,Freyre,Diego,Small
2819,10373,29,100.00,10,90.000,1,3978.51,1/31/2005 0:00,Shipped,1,...,Torikatu 38,NaN,Oulu,NaN,90110,Finland,EMEA,Koskitalo,Pirkko,Medium
2820,10386,43,100.00,10,90.000,4,5417.57,3/1/2005 0:00,Resolved,1,...,"C/ Moralzarzal, 86",NaN,Madrid,NaN,28034,Spain,EMEA,Freyre,Diego,Medium
2821,10397,34,62.24,10,56.016,1,2116.16,3/28/2005 0:00,Shipped,1,...,1 rue Alsace-Lorraine,NaN,Toulouse,NaN,31000,France,EMEA,Roulet,Annette,Small
2822,10414,47,65.52,10,58.968,9,3079.44,5/6/2005 0:00,On Hold,2,...,8616 Spinnaker Dr.,NaN,Boston,MA,51003,USA,NaN,Yoshido,Juri,Medium

In [25]:
# updating column value

df["PRICEEACH"] = df["PRICEEACH"] + 2

df

,ORDERNUMBER,QUANTITYORDERED,PRICEEACH,DISCOUNT_PERCENT,DISCOUNT,ORDERLINENUMBER,SALES,ORDERDATE,STATUS,QTR_ID,...,ADDRESSLINE1,ADDRESSLINE2,CITY,STATE,POSTALCODE,COUNTRY,TERRITORY,CONTACTLASTNAME,CONTACTFIRSTNAME,DEALSIZE
0,10107,30,97.70,10,86.130,2,2871.00,2/24/2003 0:00,Shipped,1,...,897 Long Airport Avenue,NaN,NYC,NY,10022,USA,NaN,Yu,Kwai,Small
1,10121,34,87.50,10,73.215,5,2765.90,5/7/2003 0:00,Shipped,2,...,59 rue de l'Abbaye,NaN,Reims,NaN,51100,France,EMEA,Henriot,Paul,Small
2,10134,41,96.74,10,85.266,2,3884.34,7/1/2003 0:00,Shipped,3,...,27 rue du Colonel Pierre Avia,NaN,Paris,NaN,75508,France,EMEA,Da Cunha,Daniel,Medium
3,10145,45,85.26,10,74.934,6,3746.70,8/25/2003 0:00,Shipped,3,...,78934 Hillside Dr.,NaN,Pasadena,CA,90003,USA,NaN,Young,Julie,Medium
4,10159,49,102.00,10,90.000,14,5205.27,10/10/2003 0:00,Shipped,4,...,7734 Strong St.,NaN,San Francisco,CA,NaN,USA,NaN,Brown,Julie,Medium
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2818,10350,20,102.00,10,90.000,15,2244.40,12/2/2004 0:00,Shipped,4,...,"C/ Moralzarzal, 86",NaN,Madrid,NaN,28034,Spain,EMEA,Freyre,Diego,Small
2819,10373,29,102.00,10,90.000,1,3978.51,1/31/2005 0:00,Shipped,1,...,Torikatu 38,NaN,Oulu,NaN,90110,Finland,EMEA,Koskitalo,Pirkko,Medium
2820,10386,43,102.00,10,90.000,4,5417.57,3/1/2005 0:00,Resolved,1,...,"C/ Moralzarzal, 86",NaN,Madrid,NaN,28034,Spain,EMEA,Freyre,Diego,Medium
2821,10397,34,64.24,10,56.016,1,2116.16,3/28/2005 0:00,Shipped,1,...,1 rue Alsace-Lorraine,NaN,Toulouse,NaN,31000,France,EMEA,Roulet,Annette,Small
2822,10414,47,67.52,10,58.968,9,3079.44,5/6/2005 0:00,On Hold,2,...,8616 Spinnaker Dr.,NaN,Boston,MA,51003,USA,NaN,Yoshido,Juri,Medium

In [26]:
# Removing a column
# inplace= True --> update the original dataframe, if False then it will return copy of dataframe without that column. Original dataframe will not affect.

# To remove multiple column use a list --> df.drop(columns=["DISCOUNT", "DISCOUNT_PERCENT"])

df.drop(columns="DISCOUNT", inplace=True)

df

,ORDERNUMBER,QUANTITYORDERED,PRICEEACH,DISCOUNT_PERCENT,ORDERLINENUMBER,SALES,ORDERDATE,STATUS,QTR_ID,MONTH_ID,...,ADDRESSLINE1,ADDRESSLINE2,CITY,STATE,POSTALCODE,COUNTRY,TERRITORY,CONTACTLASTNAME,CONTACTFIRSTNAME,DEALSIZE
0,10107,30,97.70,10,2,2871.00,2/24/2003 0:00,Shipped,1,2,...,897 Long Airport Avenue,NaN,NYC,NY,10022,USA,NaN,Yu,Kwai,Small
1,10121,34,87.50,10,5,2765.90,5/7/2003 0:00,Shipped,2,5,...,59 rue de l'Abbaye,NaN,Reims,NaN,51100,France,EMEA,Henriot,Paul,Small
2,10134,41,96.74,10,2,3884.34,7/1/2003 0:00,Shipped,3,7,...,27 rue du Colonel Pierre Avia,NaN,Paris,NaN,75508,France,EMEA,Da Cunha,Daniel,Medium
3,10145,45,85.26,10,6,3746.70,8/25/2003 0:00,Shipped,3,8,...,78934 Hillside Dr.,NaN,Pasadena,CA,90003,USA,NaN,Young,Julie,Medium
4,10159,49,102.00,10,14,5205.27,10/10/2003 0:00,Shipped,4,10,...,7734 Strong St.,NaN,San Francisco,CA,NaN,USA,NaN,Brown,Julie,Medium
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2818,10350,20,102.00,10,15,2244.40,12/2/2004 0:00,Shipped,4,12,...,"C/ Moralzarzal, 86",NaN,Madrid,NaN,28034,Spain,EMEA,Freyre,Diego,Small
2819,10373,29,102.00,10,1,3978.51,1/31/2005 0:00,Shipped,1,1,...,Torikatu 38,NaN,Oulu,NaN,90110,Finland,EMEA,Koskitalo,Pirkko,Medium
2820,10386,43,102.00,10,4,5417.57,3/1/2005 0:00,Resolved,1,3,...,"C/ Moralzarzal, 86",NaN,Madrid,NaN,28034,Spain,EMEA,Freyre,Diego,Medium
2821,10397,34,64.24,10,1,2116.16,3/28/2005 0:00,Shipped,1,3,...,1 rue Alsace-Lorraine,NaN,Toulouse,NaN,31000,France,EMEA,Roulet,Annette,Small
2822,10414,47,67.52,10,9,3079.44,5/6/2005 0:00,On Hold,2,5,...,8616 Spinnaker Dr.,NaN,Boston,MA,51003,USA,NaN,Yoshido,Juri,Medium

# Handling missing values in pandas

To find missing values in a DataFrame, you can use the `isnull()` method, which returns a DataFrame of the same shape with boolean values indicating whether each element is missing (True) or not (False). To get the count of missing values in each column, you can chain the `sum()` method to `isnull()`, like this: `df.isnull().sum()`. This will return a Series with the count of missing values for each column in the DataFrame.

To handle missing values, you have several options:
1. **Drop missing values**: You can use the `dropna()` method to remove rows or columns that contain missing values. For example, `df.dropna()` will drop all rows that have at least one missing value, while `df.dropna(axis=1)` will drop all columns that have at least one missing value.

2. **Fill missing values**: You can use the `fillna()` method to replace missing values with a specified value or a method. For example, `df.fillna(0)` will replace all missing values with 0, while `df.fillna(method='ffill')` will forward-fill the missing values using the last valid observation.

3. **Interpolate missing values**: You can use the `interpolate()` method to estimate missing values based on the existing data. For example, `df.interpolate(method='linear')` will perform linear interpolation to fill in the missing values.

4. **Replace missing values with the mean, median, or mode**: You can calculate the mean, median, or mode of a column and use it to fill in the missing values. For example, `df['Column_Name'].fillna(df['Column_Name'].mean(), inplace=True)` will replace missing values in 'Column_Name' with the mean of that column.

5. **Use machine learning algorithms**: For more complex datasets, you can use machine learning algorithms to predict and fill in missing values based on the patterns in the data. This approach is more advanced and may require additional libraries such as scikit-learn.

In [27]:
df.isnull().sum()

ORDERNUMBER            0
QUANTITYORDERED        0
PRICEEACH              0
DISCOUNT_PERCENT       0
ORDERLINENUMBER        0
SALES                  0
ORDERDATE              0
STATUS                 0
QTR_ID                 0
MONTH_ID               0
YEAR_ID                0
PRODUCTLINE            0
MSRP                   0
PRODUCTCODE            0
CUSTOMERNAME           0
PHONE                  0
ADDRESSLINE1           0
ADDRESSLINE2        2521
CITY                   0
STATE               1486
POSTALCODE            76
COUNTRY                0
TERRITORY           1074
CONTACTLASTNAME        0
CONTACTFIRSTNAME       0
DEALSIZE               0
dtype: int64

In [28]:
df[["STATE"]]

     STATE
0       NY
1      NaN
2      NaN
3       CA
4       CA
...    ...
2818   NaN
2819   NaN
2820   NaN
2821   NaN
2822    MA

[2823 rows x 1 columns]

In [29]:
df["STATE"].value_counts()

STATE
CA               416
MA               190
NY               178
NSW               92
Victoria          78
PA                75
CT                61
BC                48
NH                34
Tokyo             32
NV                29
Isle of Wight     26
Quebec            22
NJ                21
Osaka             20
Queensland        15
Name: count, dtype: int64

In [30]:
df["STATE"].mode()  # This return a series of data for most frequent occurring value

0    CA
Name: STATE, dtype: str

In [31]:
df["STATE"].mode()[0]   # This will return the first value of most frequent value

'CA'

In [32]:
# drop missing data row
# drop missing data for state is null as this value is important for location analysis

df.dropna(subset=["STATE"], inplace=True)

df.isnull().sum()

ORDERNUMBER            0
QUANTITYORDERED        0
PRICEEACH              0
DISCOUNT_PERCENT       0
ORDERLINENUMBER        0
SALES                  0
ORDERDATE              0
STATUS                 0
QTR_ID                 0
MONTH_ID               0
YEAR_ID                0
PRODUCTLINE            0
MSRP                   0
PRODUCTCODE            0
CUSTOMERNAME           0
PHONE                  0
ADDRESSLINE1           0
ADDRESSLINE2        1087
CITY                   0
STATE                  0
POSTALCODE            76
COUNTRY                0
TERRITORY           1074
CONTACTLASTNAME        0
CONTACTFIRSTNAME       0
DEALSIZE               0
dtype: int64

In [33]:
df["TERRITORY"]

0       NaN
3       NaN
4       NaN
5       NaN
8       NaN
       ...
2809    NaN
2810    NaN
2812    NaN
2817    NaN
2822    NaN
Name: TERRITORY, Length: 1337, dtype: str

In [34]:
# fill the missing value with most frequent value as this is a categorical data


df["TERRITORY"]= df["TERRITORY"].fillna(df["TERRITORY"].mode()[0])

df["TERRITORY"]

0       APAC
3       APAC
4       APAC
5       APAC
8       APAC
        ...
2809    APAC
2810    APAC
2812    APAC
2817    APAC
2822    APAC
Name: TERRITORY, Length: 1337, dtype: str

In [35]:

# then drop the entire column which is unnecessary

# ** once this code is run then second time it will occur an error as that column has been removed.
df.drop(columns=["ADDRESSLINE2"], inplace=True)

In [36]:
df.isnull().sum()

ORDERNUMBER          0
QUANTITYORDERED      0
PRICEEACH            0
DISCOUNT_PERCENT     0
ORDERLINENUMBER      0
SALES                0
ORDERDATE            0
STATUS               0
QTR_ID               0
MONTH_ID             0
YEAR_ID              0
PRODUCTLINE          0
MSRP                 0
PRODUCTCODE          0
CUSTOMERNAME         0
PHONE                0
ADDRESSLINE1         0
CITY                 0
STATE                0
POSTALCODE          76
COUNTRY              0
TERRITORY            0
CONTACTLASTNAME      0
CONTACTFIRSTNAME     0
DEALSIZE             0
dtype: int64

In [37]:
df[["POSTALCODE"]]

     POSTALCODE
0         10022
3         90003
4           NaN
5         94217
8           NaN
...         ...
2809      10022
2810    H1J 1C3
2812    T2F 8M4
2817      10022
2822      51003

[1337 rows x 1 columns]

In [38]:
df["POSTALCODE"]= df["POSTALCODE"].fillna("UNKNOWN")

df[["POSTALCODE"]]

     POSTALCODE
0         10022
3         90003
4       UNKNOWN
5         94217
8       UNKNOWN
...         ...
2809      10022
2810    H1J 1C3
2812    T2F 8M4
2817      10022
2822      51003

[1337 rows x 1 columns]

In [39]:
df.isnull().sum()

ORDERNUMBER         0
QUANTITYORDERED     0
PRICEEACH           0
DISCOUNT_PERCENT    0
ORDERLINENUMBER     0
SALES               0
ORDERDATE           0
STATUS              0
QTR_ID              0
MONTH_ID            0
YEAR_ID             0
PRODUCTLINE         0
MSRP                0
PRODUCTCODE         0
CUSTOMERNAME        0
PHONE               0
ADDRESSLINE1        0
CITY                0
STATE               0
POSTALCODE          0
COUNTRY             0
TERRITORY           0
CONTACTLASTNAME     0
CONTACTFIRSTNAME    0
DEALSIZE            0
dtype: int64

# Sorting and Aggregation

In [44]:
df.sort_values(by="PRICEEACH", ascending=False, inplace=True)

In [45]:
df

,ORDERNUMBER,QUANTITYORDERED,PRICEEACH,DISCOUNT_PERCENT,ORDERLINENUMBER,SALES,ORDERDATE,STATUS,QTR_ID,MONTH_ID,...,PHONE,ADDRESSLINE1,CITY,STATE,POSTALCODE,COUNTRY,TERRITORY,CONTACTLASTNAME,CONTACTFIRSTNAME,DEALSIZE
13,10263,34,102.00,10,2,3676.76,6/28/2004 0:00,Shipped,2,6,...,2035552570,25593 South Bay Ln.,Bridgewater,CT,97562,USA,APAC,King,Julie,Medium
15,10285,36,102.00,10,6,4099.68,8/27/2004 0:00,Shipped,3,8,...,6175558555,39323 Spinnaker Dr.,Cambridge,MA,51247,USA,APAC,Hernandez,Marta,Medium
19,10329,42,102.00,10,1,4396.14,11/15/2004 0:00,Shipped,4,11,...,2125557818,897 Long Airport Avenue,NYC,NY,10022,USA,APAC,Yu,Kwai,Medium
1915,10361,34,102.00,10,6,3871.92,12/17/2004 0:00,Shipped,4,12,...,+61 2 9495 8555,"Monitor Money Building, 815 Pacific Hwy",Chatswood,NSW,2067,Australia,APAC,Huxley,Adrian,Medium
1922,10124,43,102.00,10,13,5203.00,5/21/2003 0:00,Shipped,2,5,...,7025551838,8489 Strong St.,Las Vegas,NV,83030,USA,APAC,King,Sue,Medium
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1554,10312,39,31.54,10,13,1152.06,10/21/2004 0:00,Shipped,4,10,...,4155551450,5677 Strong St.,San Rafael,CA,97562,USA,APAC,Nelson,Valarie,Small
1546,10193,26,31.21,10,10,759.46,11/21/2003 0:00,Shipped,4,11,...,61-9-3844-6555,7 Allen Street,Glen Waverly,Victoria,3150,Australia,APAC,Connery,Sean,Small
1724,10195,32,30.29,10,7,905.28,11/25/2003 0:00,Shipped,4,11,...,9145554562,3758 North Pendale Street,White Plains,NY,24067,USA,APAC,Frick,Steve,Small
1543,10162,37,29.22,10,5,1007.14,10/18/2003 0:00,Shipped,4,10,...,6505551386,7734 Strong St.,San Francisco,CA,UNKNOWN,USA,APAC,Brown,Julie,Small
1563,10420,45,28.88,10,1,1209.60,5/29/2005 0:00,In Process,2,5,...,+61 2 9495 8555,"Monitor Money Building, 815 Pacific Hwy",Chatswood,NSW,2067,Australia,APAC,Huxley,Adrian,Small

In [46]:
df

,ORDERNUMBER,QUANTITYORDERED,PRICEEACH,DISCOUNT_PERCENT,ORDERLINENUMBER,SALES,ORDERDATE,STATUS,QTR_ID,MONTH_ID,...,PHONE,ADDRESSLINE1,CITY,STATE,POSTALCODE,COUNTRY,TERRITORY,CONTACTLASTNAME,CONTACTFIRSTNAME,DEALSIZE
13,10263,34,102.00,10,2,3676.76,6/28/2004 0:00,Shipped,2,6,...,2035552570,25593 South Bay Ln.,Bridgewater,CT,97562,USA,APAC,King,Julie,Medium
15,10285,36,102.00,10,6,4099.68,8/27/2004 0:00,Shipped,3,8,...,6175558555,39323 Spinnaker Dr.,Cambridge,MA,51247,USA,APAC,Hernandez,Marta,Medium
19,10329,42,102.00,10,1,4396.14,11/15/2004 0:00,Shipped,4,11,...,2125557818,897 Long Airport Avenue,NYC,NY,10022,USA,APAC,Yu,Kwai,Medium
1915,10361,34,102.00,10,6,3871.92,12/17/2004 0:00,Shipped,4,12,...,+61 2 9495 8555,"Monitor Money Building, 815 Pacific Hwy",Chatswood,NSW,2067,Australia,APAC,Huxley,Adrian,Medium
1922,10124,43,102.00,10,13,5203.00,5/21/2003 0:00,Shipped,2,5,...,7025551838,8489 Strong St.,Las Vegas,NV,83030,USA,APAC,King,Sue,Medium
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1554,10312,39,31.54,10,13,1152.06,10/21/2004 0:00,Shipped,4,10,...,4155551450,5677 Strong St.,San Rafael,CA,97562,USA,APAC,Nelson,Valarie,Small
1546,10193,26,31.21,10,10,759.46,11/21/2003 0:00,Shipped,4,11,...,61-9-3844-6555,7 Allen Street,Glen Waverly,Victoria,3150,Australia,APAC,Connery,Sean,Small
1724,10195,32,30.29,10,7,905.28,11/25/2003 0:00,Shipped,4,11,...,9145554562,3758 North Pendale Street,White Plains,NY,24067,USA,APAC,Frick,Steve,Small
1543,10162,37,29.22,10,5,1007.14,10/18/2003 0:00,Shipped,4,10,...,6505551386,7734 Strong St.,San Francisco,CA,UNKNOWN,USA,APAC,Brown,Julie,Small
1563,10420,45,28.88,10,1,1209.60,5/29/2005 0:00,In Process,2,5,...,+61 2 9495 8555,"Monitor Money Building, 815 Pacific Hwy",Chatswood,NSW,2067,Australia,APAC,Huxley,Adrian,Small

In [48]:
grouped= df.groupby(["STATUS"])["SALES"].sum()

grouped

STATUS
Cancelled       45357.66
Disputed        14378.09
In Process      57399.98
On Hold        152718.98
Resolved        44273.36
Shipped       4434965.07
Name: SALES, dtype: float64

In [49]:
multi_grouped= df.groupby(["STATUS", "COUNTRY"])["SALES"].sum()

multi_grouped

STATUS      COUNTRY
Cancelled   USA            45357.66
Disputed    Australia      14378.09
In Process  Australia      43971.43
            USA            13428.55
On Hold     USA           152718.98
Resolved    USA            44273.36
Shipped     Australia     572273.58
            Canada        224078.56
            Japan         188167.81
            UK             78240.84
            USA          3372204.28
Name: SALES, dtype: float64

# Merging and Joining